server:
  port: ${server.port}
  servlet:
    contextPath: /api
spring:
  config:
    import: classpath:/env.yml
  main:
    allow-bean-definition-overriding: true
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate: format_sql=true
  datasource:
    url: ${db.rds.url}
    username: ${db.rds.user}
    password: ${db.rds.pw}
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: ${db.redis.host}
    port: ${db.redis.port}
    database: ${db.redis.database}
  security:
    oauth:
      bsm:
        client-id: ${oauth.bsm.id}
        client-secret: ${oauth.bsm.secret}
logging:
  level:
    web: DEBUG
  org:
    hibernate:
      SQL: DEBUG
      type:
        descriptor:
          BasicBinder: TRACE
